### ISSUE TITLE
add versioning to the spec

### ISSUE THREAD

**Issue by amundo** [digitallinguistics/digitallinguistics.github.io#16]
Each version of the spec should:

1. have an inline spec number
2. have a filename with (e.g.) `text-0.1.html` (or `spec-0.1.html`, I guess, modulo our decision on whether the corpus, language, etc specs will be independent files or not)
3. The file `text.html` will always be the latest version.

This way we keep around the old versions as files, not just in git. 

Too much of a pain?

**Comment by dwhieb** [comment]
Here's a suggestion:
* Version 0.x is our current development version, which we don't bother doing versioning for (other than on GitHub) because we know it'll be changing a lot. It's the alpha.
* Version 1.x is the one we send around to people for feedback. It's the beta. Not sure if we version this on the site. I lean towards not.
* Version 2.x is our first official release of the spec. This is the one we actually start keeping track of versioning on the website for. After our first official release, we won't expect the spec to change drastically, so handling static versioning on the site is much more manageable.
* Version 3.x may never happen, but presumably would only be if we made some major changes.

We could also do versioning in the following way, so our first official release is 1.0, and maybe with luck we never have a 2.x:
* X.x
* 0.x
* 1.x
* 2.x, etc.

What do you think?

**Comment by amundo** [comment]
What would you think about numbering them as α.1 and β.1, etc? I think people think of 1.* as production/stable. So we could have an alpha (your 0), a beta (your 1), and then the launches one is 1.*? 

Using the Unicode letters would be kinda funny and linguisty (and we could just wrote alpha if we're in a hurry).

**Comment by dwhieb** [comment]
I love it! Let's do it :)

So I'll add a note about the spec being version α.1, and we can increment it each time we make revisions to the page, but not worry about a stable backup other than GitHub for now.

**Comment by dwhieb** [comment]
Since this is implemented and we have a plan for versioning going forward now, I'm closing this issue. We can reference this later once we move out of alpha.
