### ISSUE TITLE
Spec: `type`?

### ISSUE THREAD

**Issue by amundo** [digitallinguistics/digitallinguistics.github.io#30]
Again inspired by GeoJSON.

I can see a few benefits to doing something like:

    {
      "type": "text",
      "title": "Monsoon Wedding",
      "phrases": [
        {
          "id": "1",
          "startTime": "00:03:12,700",
          "endTime": "00:03:15,362",
          "transcription": "Pimmi, please bring the phone."
        },
    …
    }

For one, it would be self-documenting. People could look in the file and see what kind of thing it was. For another, it might ease the process of getting to a default rendering. We could have a default text renderer that would render everything in the text, even without a `Configuration` object (that would render all 6 of your Chitimacha orthographies!). 

Compare that to opening something like:

    {
      "type": "lexicon",
      "language": "Oxnard Mixtec"
      "words" : [
        {
          "token": "chi",
          "gloss": "because"
        },
        {
          "token": "chindeé",
          "gloss": "to.help"
        },
        …
      ]
    }

Those two seem to me like fundamental types, but one could imagine several others.

Another cool thing would be when messing with corpora: you could stuff like `lexicon.json`, `text1.json`, `text2.json`, etc, and the corpus would know how to hydrate things.

**Comment by dwhieb** [comment]
@amundo We got to talk about this briefly the other day, and I said I was all on board, so John and I began implementing this into the spec today. We added a `dataType` attribute to the text, phrase, and word objects. For the time being, we didn't add it to the participant objects, because I'm not aware of any methods we'll want on those objects yet. We can always add it later. And we'll of course want a `dataType` attribute on our other top-level objects like the lexicon as well.
